version: "3.8"

services:
  kong-database:
    image: postgres:16
    container_name: kong-database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - kong_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  kong-migrations:
    image: kong:latest
    container_name: kong-migrations
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_PG_HOST}
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
    command: kong migrations bootstrap
    depends_on:
      kong-database:
        condition: service_healthy
    networks:
      - microservices-network

  kong:
    build:
      context: .
      dockerfile: Dockerfile.kong-opa
    image: kong-custom-opa:latest
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_PG_HOST}
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      KONG_PROXY_ACCESS_LOG: ${KONG_PROXY_ACCESS_LOG}
      KONG_ADMIN_ACCESS_LOG: ${KONG_ADMIN_ACCESS_LOG}
      KONG_PROXY_ERROR_LOG: ${KONG_PROXY_ERROR_LOG}
      KONG_ADMIN_ERROR_LOG: ${KONG_ADMIN_ERROR_LOG}
      KONG_ADMIN_LISTEN: 0.0.0.0:9001, 0.0.0.0:9444 ssl
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:9002
      KONG_ADMIN_GUI_AUTH: basic
      KONG_ADMIN_GUI_SESSION_CONF: '{"secret":"changeme","cookie_secure":false}'
      KONG_ADMIN_GUI_SESSION_SECRET: changeme
    ports:
      - "8888:8000/tcp" # Kong Proxy HTTP (fixed)
      - "8443:8443/tcp" # Kong Proxy HTTPS
      - "9001:9001/tcp" # Kong Admin API HTTP
      - "9444:9444/tcp" # Kong Admin API HTTPS
      - "9002:9002/tcp" # Kong Manager OSS
    depends_on:
      kong-migrations:
        condition: service_completed_successfully
    networks:
      - microservices-network

  opa:
    image: openpolicyagent/opa:latest
    container_name: opa
    command: ["run", "--server", "--addr", "0.0.0.0:8181", "/policies"]
    volumes:
      - ./opa/policies:/policies:ro
    ports:
      - "8181:8181"
    networks:
      - microservices-network

volumes:
  kong_data:
  konga_sqlite_data:

networks:
  microservices-network:
    external: true