apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: myorg/kong-custom-opa:latest
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              value: "kong-postgres"
            - name: KONG_PG_USER
              valueFrom:
                secretKeyRef:
                  name: kong-postgres-secret
                  key: POSTGRES_USER
            - name: KONG_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kong-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: KONG_PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: kong-postgres-secret
                  key: POSTGRES_DB
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
            - name: KONG_OPA_URL
              value: "http://localhost:8181/v1/data/api/authz/allow"
          ports:
            - containerPort: 8000 # proxy
            - containerPort: 8443 # proxy SSL
            - containerPort: 8001 # admin
            - containerPort: 8444 # admin SSL
          readinessProbe:
            httpGet:
              path: /status
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
        - name: opa
          image: openpolicyagent/opa:latest
          args:
            - "run"
            - "--server"
            - "/policies/api-authz.rego"
          ports:
            - containerPort: 8181
          volumeMounts:
            - name: opa-policy
              mountPath: /policies
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
      volumes:
        - name: opa-policy
          configMap:
            name: opa-policy
