apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-ingress-controller
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-ingress-controller
  template:
    metadata:
      labels:
        app: kong-ingress-controller
    spec:
      serviceAccountName: kong-ingress
      containers:
        - name: ingress-controller
          image: kong/kubernetes-ingress-controller:2.12
          args:
            - --kong-admin-url=http://kong-admin:8001
            # Add any custom flags for your custom controller
          env:
            - name: CONTROLLER_PUBLISH_SERVICE
              value: kong/kong-proxy
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
