apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kong-ingress
rules:
  - apiGroups: [""]
    resources: [services, endpoints, pods, secrets, configmaps, nodes]
    verbs: [get, list, watch]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: [ingresses, ingressclasses]
    verbs: [get, list, watch]
  - apiGroups: ["networking.k8s.io"]
    resources: [ingressclasses]
    verbs: [get, list, watch]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch]
